AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-token-authorizer

  Sample SAM Template for lambda-token-authorizer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MyProductsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn

  MyProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./productapp
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref MyProductsAPI
            Path: /products
            Method: get

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./authorizer
      Handler: authorizer.handler
      Runtime: nodejs18.x
